### ISSUE TITLE
doesnt work for me...

### ISSUE THREAD

**Issue by cfdev** [lieser/X-Unsent_support#1]
Hi thanks for your plugin,
I have create an eml file with this:

```
X-Unsent: 1
To: tata@gmail.com
Subject: test eml support plugin
From: toto@gmail.com
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="------------boundary"

This is a multi-part message in MIME format.
--------------boundary
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

Hello world!
--------------boundary--

```

work on outlook 2010 but not thunderbird 38.6.0
an idea ?

**Comment by lieser** [comment]
Are you perhaps using a different line ending than CR+LF? I just tested it and noticed that it only works with CR+LF line ending (this will be fixed).

**Comment by cfdev** [comment]
Yeah ok I used only "\n"
thanks!

But I have an other little bug,
I have "3 email from" and when thunderbird open eml file on edit, the from email selected is not correct. when I open it on read only the from is correct.

**Comment by lieser** [comment]
That do you mean with "3 email from"? Can you please post an example?

**Comment by cfdev** [comment]
I have tree smtp account in my thunderbird ex:
toto@gmail.com, titi@gmail.com, tutu@gmail.com

In my eml file I specify the toto@gmail.com account to send my email.
When I open my eml file with your plugin, the from address selected is not the correct address specifed in the eml file.

**Comment by lieser** [comment]
Please try the new version 1.1.0 (https://addons.mozilla.org/en-US/thunderbird/addon/x-unsent-support/versions/).
LF line ending should now work. Also the sending identity is now selected based on the from address.

**Comment by cfdev** [comment]
Many thanks it's works perfectly !!
Strange that function doesn't existe natively on thunderbird....
