### ISSUE TITLE
embedded image not show

### ISSUE THREAD

**Issue by tothpaul** [lieser/X-Unsent_support#3]
I have an EML file with HTML and an embedded image, the image is not displayed whenever Thunderbird is not launched first.

close Thunderbird, dblClick on the EML file, the image is broken

start Thunderbird, dblClick on the EML, the image is ok.

(EML not supported by Github)
[MAIL.EML.TXT](https://github.com/lieser/X-Unsent_support/files/1674448/MAIL.EML.TXT)

**Comment by lieser** [comment]
Thanks for reporting. I just had a quick look at it, but could not find a solution. As this add-on is only in very low maintenance mode right know (which will probably also not change), I also don't see myself investing any more time into fixing this issue. Pull request are always welcome.

Below my finding so far (for feature self, or anyone else trying to fix this):
Broken image: the image src attribute is `data:image/png;base64,`
Working image: the image src attribute is `data:image/png;base64,<the encoded image date from the eml file, starting with R0lGODlhPQBEAP...>`

From my current understanding, the replacing of the src attribute `cid:image0.png` in the email to `data:image/png;base64,R0lGODlhPQBEAP...` should happen in https://dxr.mozilla.org/comm-central/source/mailnews/mime/src/mimemrel.cpp.
Why the replacing fails is still unclear. Probably some shared component (which is normally loaded by the main window) is not loaded/initialized by the `MailServices.compose.OpenComposeWindow()` call, which is currently used by the add-on to open the compose window.

**Comment by tothpaul** [comment]
thank's for the reply anyway ;)

**Comment by lieser** [comment]
Just tested it with the new 4.0.0 version in TB 78.
There the bus is shown in the edit view. As I did not change anything relevant in the add-on about it, it was probably fixed inside Thunderbird.

Can you confirm that this now works for you?

**Comment by tothpaul** [comment]
Hi,

the image is fine, but the email isn't in  send state (I have to click on Message/Edit...)...anyway thank you very much for the new version !

EDIT: this is the case for any mail when TB is not started....I don't remember if it was already the case :)

Paul

**Comment by lieser** [comment]
I think you are talking about #6, which unfortunately I think is not something that can be fixed (which is why I closed it as wont fix). Reopened it to make that (know) issue more visible.

Will close this issue, as the embedded images should work now.
