### ISSUE TITLE
Thunderbird 78+

### ISSUE THREAD

**Issue by biose** [lieser/X-Unsent_support#7]
Hello,

Can you modify the code to make it work for Thunderbird 78+
As long as Thunderbird does not support X-Unsent, your extension will be essential for many users.

Thanks
Best regards

**Comment by lieser** [comment]
I have not yet decide if I will try to update the extension for 78.
But I will definitely not look into it before I am finished with porting my other add-on (DKIM Verifier), which I expect to still take a couple of weeks.

So even if an update is coming (and that is a big if), don't expect it anytime soon.

If anyone is interested in helping porting it, pull request are of course always welcomed.

**Comment by luetm** [comment]
Hey! We use this addon to add support for customers to send emails out of our application (mainly to avoid MAPI). So far we've been very happy! Do you have an updated schedule for the support for the new TB version?

**Comment by lieser** [comment]
Unfortunately I am stills busy with updating my other add-on, so had not time yet to look into this.

Note that someone made an add-on to open an eml file in the editor via a button. Not a full replacement, as this will not work with simply double clicking the eml file. But might still be helpful for some:
- https://addons.thunderbird.net/thunderbird/addon/elm-editor/
- https://github.com/pgpgeek/thunderbird-addon-eml-editor

**Comment by lieser** [comment]
I just released a new version 4.0.0 that should work in TB 78. It is currently in review on ATN, but you can already get it from https://github.com/lieser/X-Unsent_support/releases.
